### ISSUE TITLE
Module build failed: Error: Emit skipped

### ISSUE THREAD

**Issue by playground** [amcdnl/ng2-three#2]
ERROR in ./src/bootstrap.ts
Module build failed: Error: Emit skipped
    at State.emit (/Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/awesome-typescript-loader/src/host.ts:254:19)
    at transform (/Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/awesome-typescript-loader/src/index.ts:147:28)
    at transformationFunction (/Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/awesome-typescript-loader/src/index.ts:89:48)
    at compiler (/Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/awesome-typescript-loader/src/index.ts:105:34)
    at Object.loader (/Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi bootstrap

ERROR in [default] /Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/@angular/common/src/pipes/async_pipe.d.ts:44:37 
Cannot find name 'Promise'.

ERROR in [default] /Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/@angular/compiler/src/directive_normalizer.d.ts:19:99 
Cannot find name 'Promise'.

ERROR in [default] /Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/@angular/compiler/src/directive_normalizer.d.ts:21:73 
Cannot find name 'Promise'.

ERROR in [default] /Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/@angular/compiler/src/offline_compiler.d.ts:33:123 
Cannot find name 'Promise'.

ERROR in [default] /Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/@angular/compiler/src/resource_loader.d.ts:13:22 
Cannot find name 'Promise'.

ERROR in [default] /Users/ljeff/git_repo/sandbox/webvr/ng2-three-demo/node_modules/@angular/compiler/src/runtime_compiler.d.ts:42:48 
Cannot find name 'Promise'.

**Comment by sancelot** [comment]
modify tsconfig.json and add following compilerOptions

   "lib": ["es6", "dom"]
